"""
Avoidance Strategies Module

Defines different strategies for avoiding obstacles:
- Stop and hover
- Dodge (lateral movement)
- Climb/descend
- Reverse
- Follow path
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional, Dict, Tuple, Any
from abc import ABC, abstractmethod
import math

from .obstacle_tracker import TrackedObstacle, ObstaclePosition, ObstacleVelocity
from .collision_detector import CollisionPrediction, CollisionSeverity, DroneState


class AvoidanceAction(Enum):
    """Type of avoidance action."""
    NONE = "none"               # No action needed
    STOP = "stop"               # Stop and hover
    SLOW_DOWN = "slow_down"     # Reduce speed
    DODGE_LEFT = "dodge_left"   # Move left
    DODGE_RIGHT = "dodge_right" # Move right
    CLIMB = "climb"             # Increase altitude
    DESCEND = "descend"         # Decrease altitude
    REVERSE = "reverse"         # Move backward
    DETOUR = "detour"           # Take alternate path


@dataclass
class AvoidanceCommand:
    """Command generated by avoidance strategy."""
    action: AvoidanceAction = AvoidanceAction.NONE

    # Velocity adjustments
    velocity: Tuple[float, float, float] = (0, 0, 0)  # (vx, vy, vz) m/s

    # Position target (optional)
    target_position: Optional[Tuple[float, float, float]] = None

    # Duration
    duration: float = 0.0       # seconds

    # Priority/urgency
    priority: float = 0.0       # 0-1

    # Metadata
    reason: str = ""
    obstacle_id: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'action': self.action.value,
            'velocity': self.velocity,
            'target_position': self.target_position,
            'duration': self.duration,
            'priority': self.priority,
            'reason': self.reason,
            'obstacle_id': self.obstacle_id,
        }


class AvoidanceStrategy(ABC):
    """Abstract base class for avoidance strategies."""

    @property
    @abstractmethod
    def name(self) -> str:
        """Strategy name."""
        pass

    @abstractmethod
    def compute_avoidance(
        self,
        drone_state: DroneState,
        prediction: CollisionPrediction,
        constraints: Optional[Dict[str, Any]] = None,
    ) -> AvoidanceCommand:
        """
        Compute avoidance command for a collision prediction.

        Args:
            drone_state: Current drone state
            prediction: Collision prediction to avoid
            constraints: Optional constraints (max speed, geofence, etc.)

        Returns:
            AvoidanceCommand to execute
        """
        pass

    @abstractmethod
    def is_applicable(
        self,
        drone_state: DroneState,
        prediction: CollisionPrediction,
    ) -> bool:
        """Check if this strategy is applicable to the situation."""
        pass


class StopStrategy(AvoidanceStrategy):
    """Emergency stop and hover strategy."""

    @property
    def name(self) -> str:
        return "stop"

    def compute_avoidance(
        self,
        drone_state: DroneState,
        prediction: CollisionPrediction,
        constraints: Optional[Dict[str, Any]] = None,
    ) -> AvoidanceCommand:
        """Stop all movement immediately."""
        return AvoidanceCommand(
            action=AvoidanceAction.STOP,
            velocity=(0, 0, 0),
            duration=2.0,
            priority=1.0,
            reason="Emergency stop - obstacle detected",
            obstacle_id=prediction.obstacle.id,
        )

    def is_applicable(
        self,
        drone_state: DroneState,
        prediction: CollisionPrediction,
    ) -> bool:
        """Applicable when very close to obstacle."""
        return prediction.severity == CollisionSeverity.CRITICAL


class SlowDownStrategy(AvoidanceStrategy):
    """Reduce speed to allow more reaction time."""

    @property
    def name(self) -> str:
        return "slow_down"

    def compute_avoidance(
        self,
        drone_state: DroneState,
        prediction: CollisionPrediction,
        constraints: Optional[Dict[str, Any]] = None,
    ) -> AvoidanceCommand:
        """Reduce speed by 50%."""
        vx = drone_state.velocity.vx * 0.5
        vy = drone_state.velocity.vy * 0.5
        vz = drone_state.velocity.vz * 0.5

        return AvoidanceCommand(
            action=AvoidanceAction.SLOW_DOWN,
            velocity=(vx, vy, vz),
            duration=3.0,
            priority=0.5,
            reason="Reducing speed due to obstacle ahead",
            obstacle_id=prediction.obstacle.id,
        )

    def is_applicable(
        self,
        drone_state: DroneState,
        prediction: CollisionPrediction,
    ) -> bool:
        """Applicable when obstacle is detected but not critical."""
        return prediction.severity in [CollisionSeverity.MEDIUM, CollisionSeverity.HIGH]


class DodgeStrategy(AvoidanceStrategy):
    """Lateral dodge maneuver."""

    def __init__(self, dodge_speed: float = 3.0):
        self.dodge_speed = dodge_speed

    @property
    def name(self) -> str:
        return "dodge"

    def compute_avoidance(
        self,
        drone_state: DroneState,
        prediction: CollisionPrediction,
        constraints: Optional[Dict[str, Any]] = None,
    ) -> AvoidanceCommand:
        """Dodge left or right based on obstacle position."""
        obstacle = prediction.obstacle

        # Calculate direction to obstacle
        dx = obstacle.position.x - drone_state.position.x
        dy = obstacle.position.y - drone_state.position.y

        # Calculate perpendicular direction (dodge direction)
        # Choose the direction that moves away from obstacle
        # Perpendicular to obstacle direction
        perp_left = (-dy, dx)
        perp_right = (dy, -dx)

        # Normalize
        mag = math.sqrt(perp_left[0]**2 + perp_left[1]**2)
        if mag > 0:
            perp_left = (perp_left[0]/mag, perp_left[1]/mag)
            perp_right = (perp_right[0]/mag, perp_right[1]/mag)
        else:
            perp_left = (0, 1)
            perp_right = (0, -1)

        # Choose direction that has more clearance
        # For simplicity, prefer right dodge unless obstacle is on right
        if dy > 0:  # Obstacle is to the right
            dodge_dir = perp_left
            action = AvoidanceAction.DODGE_LEFT
        else:
            dodge_dir = perp_right
            action = AvoidanceAction.DODGE_RIGHT

        # Calculate velocity
        vx = dodge_dir[0] * self.dodge_speed
        vy = dodge_dir[1] * self.dodge_speed

        # Maintain some forward velocity if not critical
        if prediction.severity != CollisionSeverity.CRITICAL:
            vx += drone_state.velocity.vx * 0.3

        return AvoidanceCommand(
            action=action,
            velocity=(vx, vy, 0),
            duration=2.0,
            priority=0.7,
            reason=f"Dodging {'left' if action == AvoidanceAction.DODGE_LEFT else 'right'}",
            obstacle_id=prediction.obstacle.id,
        )

    def is_applicable(
        self,
        drone_state: DroneState,
        prediction: CollisionPrediction,
    ) -> bool:
        """Applicable when there's lateral clearance."""
        return prediction.severity in [
            CollisionSeverity.HIGH,
            CollisionSeverity.CRITICAL,
        ]


class ClimbStrategy(AvoidanceStrategy):
    """Climb over obstacle."""

    def __init__(self, climb_rate: float = 3.0, max_altitude: float = 120.0):
        self.climb_rate = climb_rate
        self.max_altitude = max_altitude

    @property
    def name(self) -> str:
        return "climb"

    def compute_avoidance(
        self,
        drone_state: DroneState,
        prediction: CollisionPrediction,
        constraints: Optional[Dict[str, Any]] = None,
    ) -> AvoidanceCommand:
        """Climb over the obstacle."""
        obstacle = prediction.obstacle

        # Calculate how much to climb
        current_alt = -drone_state.position.z  # NED to altitude
        obstacle_top = -obstacle.position.z + obstacle.height / 2
        clearance = 3.0  # meters above obstacle

        target_alt = obstacle_top + clearance

        # Check altitude limit
        max_alt = self.max_altitude
        if constraints:
            max_alt = constraints.get('max_altitude', self.max_altitude)

        target_alt = min(target_alt, max_alt)

        # Climb velocity (negative z in NED = up)
        vz = -self.climb_rate if target_alt > current_alt else 0

        return AvoidanceCommand(
            action=AvoidanceAction.CLIMB,
            velocity=(drone_state.velocity.vx * 0.5, drone_state.velocity.vy * 0.5, vz),
            duration=3.0,
            priority=0.6,
            reason=f"Climbing over obstacle to {target_alt:.1f}m",
            obstacle_id=prediction.obstacle.id,
        )

    def is_applicable(
        self,
        drone_state: DroneState,
        prediction: CollisionPrediction,
    ) -> bool:
        """Applicable when we can climb and obstacle is below max altitude."""
        obstacle = prediction.obstacle
        obstacle_top = -obstacle.position.z + obstacle.height / 2

        # Check if we can climb over
        return obstacle_top < self.max_altitude - 5


class DescendStrategy(AvoidanceStrategy):
    """Descend under obstacle."""

    def __init__(self, descent_rate: float = 2.0, min_altitude: float = 5.0):
        self.descent_rate = descent_rate
        self.min_altitude = min_altitude

    @property
    def name(self) -> str:
        return "descend"

    def compute_avoidance(
        self,
        drone_state: DroneState,
        prediction: CollisionPrediction,
        constraints: Optional[Dict[str, Any]] = None,
    ) -> AvoidanceCommand:
        """Descend under the obstacle."""
        obstacle = prediction.obstacle

        # Calculate how much to descend
        current_alt = -drone_state.position.z
        obstacle_bottom = -obstacle.position.z - obstacle.height / 2
        clearance = 3.0

        target_alt = obstacle_bottom - clearance

        # Check minimum altitude
        min_alt = self.min_altitude
        if constraints:
            min_alt = constraints.get('min_altitude', self.min_altitude)

        target_alt = max(target_alt, min_alt)

        # Descent velocity (positive z in NED = down)
        vz = self.descent_rate if target_alt < current_alt else 0

        return AvoidanceCommand(
            action=AvoidanceAction.DESCEND,
            velocity=(drone_state.velocity.vx * 0.5, drone_state.velocity.vy * 0.5, vz),
            duration=3.0,
            priority=0.5,
            reason=f"Descending under obstacle to {target_alt:.1f}m",
            obstacle_id=prediction.obstacle.id,
        )

    def is_applicable(
        self,
        drone_state: DroneState,
        prediction: CollisionPrediction,
    ) -> bool:
        """Applicable when obstacle is above us and we have room to descend."""
        obstacle = prediction.obstacle
        obstacle_bottom = -obstacle.position.z - obstacle.height / 2
        current_alt = -drone_state.position.z

        # Check if obstacle is above us and we can descend
        return obstacle_bottom > current_alt and obstacle_bottom > self.min_altitude + 5


class ReverseStrategy(AvoidanceStrategy):
    """Reverse away from obstacle."""

    def __init__(self, reverse_speed: float = 2.0):
        self.reverse_speed = reverse_speed

    @property
    def name(self) -> str:
        return "reverse"

    def compute_avoidance(
        self,
        drone_state: DroneState,
        prediction: CollisionPrediction,
        constraints: Optional[Dict[str, Any]] = None,
    ) -> AvoidanceCommand:
        """Move backward away from obstacle."""
        obstacle = prediction.obstacle

        # Calculate direction away from obstacle
        dx = drone_state.position.x - obstacle.position.x
        dy = drone_state.position.y - obstacle.position.y

        dist = math.sqrt(dx*dx + dy*dy)
        if dist > 0:
            dx, dy = dx/dist, dy/dist
        else:
            # Default to backward
            heading_rad = math.radians(drone_state.heading)
            dx = -math.cos(heading_rad)
            dy = -math.sin(heading_rad)

        vx = dx * self.reverse_speed
        vy = dy * self.reverse_speed

        return AvoidanceCommand(
            action=AvoidanceAction.REVERSE,
            velocity=(vx, vy, 0),
            duration=2.0,
            priority=0.8,
            reason="Reversing away from obstacle",
            obstacle_id=prediction.obstacle.id,
        )

    def is_applicable(
        self,
        drone_state: DroneState,
        prediction: CollisionPrediction,
    ) -> bool:
        """Applicable when critical and other options unavailable."""
        return prediction.severity == CollisionSeverity.CRITICAL


class AvoidanceStrategySelector:
    """
    Selects the best avoidance strategy based on the situation.
    """

    def __init__(self):
        self._strategies: List[AvoidanceStrategy] = [
            StopStrategy(),
            SlowDownStrategy(),
            DodgeStrategy(),
            ClimbStrategy(),
            DescendStrategy(),
            ReverseStrategy(),
        ]

    def select_strategy(
        self,
        drone_state: DroneState,
        prediction: CollisionPrediction,
        constraints: Optional[Dict[str, Any]] = None,
    ) -> Tuple[AvoidanceStrategy, AvoidanceCommand]:
        """
        Select best avoidance strategy for the situation.

        Args:
            drone_state: Current drone state
            prediction: Collision prediction
            constraints: Flight constraints

        Returns:
            Tuple of (selected strategy, avoidance command)
        """
        best_strategy = None
        best_command = None
        best_score = -1

        for strategy in self._strategies:
            if not strategy.is_applicable(drone_state, prediction):
                continue

            command = strategy.compute_avoidance(drone_state, prediction, constraints)
            score = self._score_command(command, prediction, constraints)

            if score > best_score:
                best_score = score
                best_strategy = strategy
                best_command = command

        # Default to stop if no strategy applicable
        if best_strategy is None:
            best_strategy = self._strategies[0]  # StopStrategy
            best_command = best_strategy.compute_avoidance(drone_state, prediction, constraints)

        return best_strategy, best_command

    def _score_command(
        self,
        command: AvoidanceCommand,
        prediction: CollisionPrediction,
        constraints: Optional[Dict[str, Any]] = None,
    ) -> float:
        """Score an avoidance command."""
        score = command.priority

        # Prefer commands that maintain mission progress
        if command.action == AvoidanceAction.SLOW_DOWN:
            score += 0.1
        elif command.action in [AvoidanceAction.DODGE_LEFT, AvoidanceAction.DODGE_RIGHT]:
            score += 0.05

        # Penalize reversing (loses progress)
        if command.action == AvoidanceAction.REVERSE:
            score -= 0.1

        # Check constraint violations
        if constraints:
            if command.target_position:
                x, y, z = command.target_position
                # Check altitude limits
                alt = -z
                if alt > constraints.get('max_altitude', 120):
                    score -= 0.5
                if alt < constraints.get('min_altitude', 5):
                    score -= 0.5

        return score

    def get_multiple_options(
        self,
        drone_state: DroneState,
        prediction: CollisionPrediction,
        constraints: Optional[Dict[str, Any]] = None,
        max_options: int = 3,
    ) -> List[Tuple[AvoidanceStrategy, AvoidanceCommand]]:
        """Get multiple avoidance options ranked by preference."""
        options = []

        for strategy in self._strategies:
            if not strategy.is_applicable(drone_state, prediction):
                continue

            command = strategy.compute_avoidance(drone_state, prediction, constraints)
            score = self._score_command(command, prediction, constraints)
            options.append((score, strategy, command))

        # Sort by score descending
        options.sort(key=lambda x: -x[0])

        return [(s, c) for _, s, c in options[:max_options]]
